---
Resources:
  TUDublinEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: us-east-1a
      InstanceType: t2.micro
      KeyName: TU_Dublin
      ImageId: ami-0557a15b87f6559cf
  TUDublinS3Bucket12345:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
