---
Parameters:
  AvailabilityZone:
    Type: String
    Default: eu-west-1a
    AllowedValues:
      - us-east-1a
      - us-east-1b
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.micro
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: TU_Dublin
  ImageId:
    Type: String
    Default: ami-0557a15b87f6559cf
    AllowedValues:
      - ami-0dfcb1ef8550277af
      - ami-0557a15b87f6559cf

Resources:
  TUDublinEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
